prompt --application/pages/page_00012
begin
--   Manifest
--     PAGE: 00012
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2026.03.30'
,p_release=>'26.1.2'
,p_default_workspace_id=>25107497146013559697
,p_default_application_id=>156207
,p_default_id_offset=>8982783537607029
,p_default_owner=>'WKSP_EMADFLOW'
);
wwv_flow_imp_page.create_page(
 p_id=>12
,p_name=>'Welcome & Getting Started'
,p_alias=>'WELCOME-GETTING-STARTED'
,p_step_title=>'Welcome & Getting Started'
,p_autocomplete_on_off=>'OFF'
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* ============================================================',
'   EMADFLOW',
'   PAGE 12 - WELCOME & GETTING STARTED',
'   MASTER INLINE CSS',
'   ============================================================ */',
'',
':root {',
'    --emad-guide-primary: #11877f;',
'    --emad-guide-primary-dark: #086c66;',
'    --emad-guide-primary-soft: #eaf7f5;',
'    --emad-guide-text: #1f2933;',
'    --emad-guide-muted: #68737d;',
'    --emad-guide-border: #dfe8e7;',
'    --emad-guide-surface: #ffffff;',
'    --emad-guide-soft: #f6f9f9;',
'}',
'',
'',
'/* ============================================================',
'   PAGE',
'   ============================================================ */',
'',
'.t-Body-contentInner {',
'    max-width: 1180px;',
'    margin-left: auto;',
'    margin-right: auto;',
'}',
'',
'.t-Body-main {',
'    background:',
'        linear-gradient(',
'            180deg,',
'            #f5fbfa 0,',
'            #ffffff 420px',
'        );',
'}',
'',
'',
'/* ============================================================',
'   HERO',
'   ============================================================ */',
'',
'#emad-guide-hero {',
'    margin-top: 22px;',
'    margin-bottom: 34px;',
'}',
'',
'.emad-guide-hero {',
'    position: relative;',
'',
'    padding:',
'        54px 34px 48px 34px;',
'',
'    text-align: center;',
'',
'    background:',
'        linear-gradient(',
'            135deg,',
'            #ffffff 0%,',
'            #edf9f7 55%,',
'            #e4f5f2 100%',
'        );',
'',
'    border:',
'        1px solid #d7e9e6;',
'',
'    border-radius: 24px;',
'',
'    overflow: hidden;',
'',
'    box-shadow:',
'        0 12px 34px',
'        rgba(17, 135, 127, 0.10);',
'}',
'',
'.emad-guide-hero::before {',
'    content: "";',
'',
'    position: absolute;',
'',
'    width: 260px;',
'    height: 260px;',
'',
'    top: -140px;',
'    right: -100px;',
'',
'    border-radius: 50%;',
'',
'    background:',
'        rgba(17, 135, 127, 0.08);',
'}',
'',
'.emad-guide-hero::after {',
'    content: "";',
'',
'    position: absolute;',
'',
'    width: 180px;',
'    height: 180px;',
'',
'    bottom: -115px;',
'    left: -60px;',
'',
'    border-radius: 50%;',
'',
'    background:',
'        rgba(17, 135, 127, 0.06);',
'}',
'',
'.emad-guide-hero-icon {',
'    position: relative;',
'    z-index: 1;',
'',
'    display: inline-flex;',
'',
'    width: 68px;',
'    height: 68px;',
'',
'    align-items: center;',
'    justify-content: center;',
'',
'    margin-bottom: 15px;',
'',
'    border-radius: 20px;',
'',
'    background:',
'        var(--emad-guide-primary);',
'',
'    color: #ffffff;',
'',
'    font-size: 29px;',
'',
'    box-shadow:',
'        0 8px 20px',
'        rgba(17, 135, 127, 0.22);',
'}',
'',
'.emad-guide-beta-badge {',
'    position: relative;',
'    z-index: 1;',
'',
'    display: table;',
'',
'    margin:',
'        0 auto 12px auto;',
'',
'    padding:',
'        5px 10px;',
'',
'    font-size: 0.72rem;',
'    font-weight: 700;',
'',
'    letter-spacing: 0.08em;',
'',
'    color:',
'        var(--emad-guide-primary-dark);',
'',
'    background:',
'        rgba(255, 255, 255, 0.8);',
'',
'    border:',
'        1px solid #cfe6e2;',
'',
'    border-radius: 999px;',
'}',
'',
'.emad-guide-hero h1 {',
'    position: relative;',
'    z-index: 1;',
'',
'    margin:',
'        0 0 8px 0;',
'',
'    color:',
'        var(--emad-guide-text);',
'',
'    font-size:',
'        clamp(2rem, 5vw, 3.2rem);',
'',
'    line-height: 1.08;',
'',
'    font-weight: 800;',
'}',
'',
'.emad-guide-welcome-name {',
'    position: relative;',
'    z-index: 1;',
'',
'    margin:',
'        0 0 18px 0;',
'',
'    color:',
'        var(--emad-guide-primary-dark);',
'',
'    font-weight: 700;',
'',
'    font-size: 1.05rem;',
'}',
'',
'.emad-guide-hero-lead {',
'    position: relative;',
'    z-index: 1;',
'',
'    max-width: 760px;',
'',
'    margin:',
'        0 auto;',
'',
'    color:',
'        var(--emad-guide-muted);',
'',
'    font-size: 1.08rem;',
'    line-height: 1.7;',
'}',
'',
'.emad-guide-hero-pills {',
'    position: relative;',
'    z-index: 1;',
'',
'    display: flex;',
'    flex-wrap: wrap;',
'    justify-content: center;',
'',
'    gap: 9px;',
'',
'    margin-top: 25px;',
'}',
'',
'.emad-guide-hero-pills > span {',
'    display: inline-flex;',
'',
'    align-items: center;',
'',
'    gap: 7px;',
'',
'    padding:',
'        7px 11px;',
'',
'    background:',
'        rgba(255, 255, 255, 0.85);',
'',
'    border:',
'        1px solid #d8e8e6;',
'',
'    border-radius: 999px;',
'',
'    color:',
'        #51605f;',
'',
'    font-size: 0.84rem;',
'}',
'',
'',
'/* ============================================================',
'   FEATURE CARDS',
'   ============================================================ */',
'',
'#emad-guide-features {',
'    margin-top: 32px;',
'    margin-bottom: 46px;',
'}',
'',
'#emad-guide-features .t-Region-title {',
'    font-weight: 750;',
'}',
'',
'',
'/* Force four equal feature cards on wide screens */',
'',
'#emad-guide-features .a-CardView-items {',
'    display: grid !important;',
'',
'    grid-template-columns:',
'        repeat(',
'            4,',
'            minmax(0, 1fr)',
'        ) !important;',
'',
'    gap: 16px !important;',
'',
'    width: 100% !important;',
'}',
'',
'#emad-guide-features .a-CardView-item {',
'    width: 100% !important;',
'    max-width: none !important;',
'    min-width: 0 !important;',
'',
'    border:',
'        1px solid',
'        var(--emad-guide-border);',
'',
'    border-radius: 16px;',
'',
'    overflow: hidden;',
'',
'    box-shadow:',
'        0 3px 10px',
'        rgba(0, 0, 0, 0.04);',
'',
'    transition:',
'        transform 0.16s ease,',
'        box-shadow 0.16s ease,',
'        border-color 0.16s ease;',
'}',
'',
'#emad-guide-features .a-CardView-item:hover {',
'    transform:',
'        translateY(-3px);',
'',
'    border-color:',
'        #bcded9;',
'',
'    box-shadow:',
'        0 10px 22px',
'        rgba(0, 0, 0, 0.07);',
'}',
'',
'#emad-guide-features .a-CardView-title {',
'    font-weight: 750;',
'}',
'',
'#emad-guide-features .a-CardView-badge {',
'    border-radius: 999px;',
'}',
'',
'',
'/* ============================================================',
'   SHARED SECTION',
'   ============================================================ */',
'',
'.emad-guide-section {',
'    margin:',
'        44px 0;',
'}',
'',
'.emad-guide-section-heading {',
'    max-width: 760px;',
'',
'    margin-bottom: 24px;',
'}',
'',
'.emad-guide-eyebrow {',
'    display: inline-block;',
'',
'    margin-bottom: 8px;',
'',
'    color:',
'        var(--emad-guide-primary);',
'',
'    font-size: 0.74rem;',
'',
'    font-weight: 800;',
'',
'    letter-spacing: 0.11em;',
'}',
'',
'.emad-guide-section-heading h2,',
'.emad-guide-cta h2 {',
'    margin:',
'        0 0 9px 0;',
'',
'    color:',
'        var(--emad-guide-text);',
'',
'    font-weight: 750;',
'',
'    line-height: 1.25;',
'}',
'',
'.emad-guide-section-heading p,',
'.emad-guide-cta p {',
'    margin: 0;',
'',
'    color:',
'        var(--emad-guide-muted);',
'',
'    line-height: 1.6;',
'}',
'',
'',
'/* ============================================================',
'   STEPS',
'   ============================================================ */',
'',
'.emad-guide-steps {',
'    position: relative;',
'',
'    padding-left: 10px;',
'}',
'',
'.emad-guide-step {',
'    position: relative;',
'',
'    display: grid;',
'',
'    grid-template-columns:',
'        52px minmax(0, 1fr);',
'',
'    gap: 18px;',
'',
'    padding-bottom: 24px;',
'}',
'',
'.emad-guide-step:not(:last-child)::before {',
'    content: "";',
'',
'    position: absolute;',
'',
'    left: 25px;',
'    top: 45px;',
'    bottom: -2px;',
'',
'    width: 2px;',
'',
'    background:',
'        #d7e8e5;',
'}',
'',
'.emad-guide-step-number {',
'    position: relative;',
'    z-index: 1;',
'',
'    display: flex;',
'',
'    width: 52px;',
'    height: 52px;',
'',
'    align-items: center;',
'    justify-content: center;',
'',
'    border-radius: 16px;',
'',
'    background:',
'        var(--emad-guide-primary);',
'',
'    color: #ffffff;',
'',
'    font-weight: 800;',
'',
'    box-shadow:',
'        0 5px 13px',
'        rgba(17, 135, 127, 0.18);',
'}',
'',
'.emad-guide-step-content {',
'    padding:',
'        4px 0 0 0;',
'}',
'',
'.emad-guide-step-content h3 {',
'    margin:',
'        0 0 6px 0;',
'',
'    color:',
'        var(--emad-guide-text);',
'',
'    font-size: 1rem;',
'',
'    font-weight: 750;',
'}',
'',
'.emad-guide-step-content p {',
'    margin: 0;',
'',
'    max-width: 820px;',
'',
'    color:',
'        var(--emad-guide-muted);',
'',
'    line-height: 1.6;',
'}',
'',
'',
'/* ============================================================',
'   DASHBOARD EXPLAINER',
'   ============================================================ */',
'',
'.emad-guide-dashboard-grid {',
'    display: grid;',
'',
'    grid-template-columns:',
'        repeat(',
'            3,',
'            minmax(0, 1fr)',
'        );',
'',
'    gap: 15px;',
'}',
'',
'.emad-guide-info-card {',
'    padding: 22px;',
'',
'    background:',
'        var(--emad-guide-surface);',
'',
'    border:',
'        1px solid',
'        var(--emad-guide-border);',
'',
'    border-radius: 16px;',
'',
'    box-shadow:',
'        0 2px 8px',
'        rgba(0, 0, 0, 0.035);',
'',
'    transition:',
'        transform 0.15s ease,',
'        box-shadow 0.15s ease;',
'}',
'',
'.emad-guide-info-card:hover {',
'    transform:',
'        translateY(-2px);',
'',
'    box-shadow:',
'        0 8px 18px',
'        rgba(0, 0, 0, 0.06);',
'}',
'',
'.emad-guide-info-icon {',
'    display: flex;',
'',
'    width: 42px;',
'    height: 42px;',
'',
'    align-items: center;',
'    justify-content: center;',
'',
'    margin-bottom: 13px;',
'',
'    color:',
'        var(--emad-guide-primary-dark);',
'',
'    background:',
'        var(--emad-guide-primary-soft);',
'',
'    border-radius: 12px;',
'',
'    font-size: 17px;',
'}',
'',
'.emad-guide-info-card h3 {',
'    margin:',
'        0 0 7px 0;',
'',
'    color:',
'        var(--emad-guide-text);',
'',
'    font-size: 1rem;',
'',
'    font-weight: 750;',
'}',
'',
'.emad-guide-info-card p {',
'    margin: 0;',
'',
'    color:',
'        var(--emad-guide-muted);',
'',
'    line-height: 1.55;',
'',
'    font-size: 0.9rem;',
'}',
'',
'',
'/* ============================================================',
'   TIPS',
'   ============================================================ */',
'',
'.emad-guide-tips-section {',
'    padding: 28px;',
'',
'    background:',
'        var(--emad-guide-soft);',
'',
'    border:',
'        1px solid',
'        var(--emad-guide-border);',
'',
'    border-radius: 18px;',
'}',
'',
'.emad-guide-tip-list {',
'    display: grid;',
'',
'    grid-template-columns:',
'        repeat(',
'            2,',
'            minmax(0, 1fr)',
'        );',
'',
'    gap: 14px;',
'}',
'',
'.emad-guide-tip {',
'    display: flex;',
'',
'    gap: 12px;',
'',
'    padding: 16px;',
'',
'    background: #ffffff;',
'',
'    border:',
'        1px solid #e3ebea;',
'',
'    border-radius: 13px;',
'}',
'',
'.emad-guide-tip > .fa {',
'    margin-top: 2px;',
'',
'    color:',
'        var(--emad-guide-primary);',
'',
'    font-size: 18px;',
'}',
'',
'.emad-guide-tip strong {',
'    color:',
'        var(--emad-guide-text);',
'}',
'',
'.emad-guide-tip p {',
'    margin:',
'        4px 0 0 0;',
'',
'    color:',
'        var(--emad-guide-muted);',
'',
'    font-size: 0.88rem;',
'',
'    line-height: 1.5;',
'}',
'',
'',
'/* ============================================================',
'   PRIVACY / BETA',
'   ============================================================ */',
'',
'#emad-guide-privacy {',
'    margin:',
'        36px 0;',
'}',
'',
'.emad-guide-privacy {',
'    display: flex;',
'',
'    align-items: flex-start;',
'',
'    gap: 16px;',
'',
'    padding: 22px;',
'',
'    background:',
'        #f1f8fb;',
'',
'    border:',
'        1px solid #d5e7ef;',
'',
'    border-radius: 16px;',
'}',
'',
'.emad-guide-privacy-icon {',
'    display: flex;',
'',
'    flex: 0 0 auto;',
'',
'    width: 45px;',
'    height: 45px;',
'',
'    align-items: center;',
'    justify-content: center;',
'',
'    color: #216b88;',
'',
'    background: #ffffff;',
'',
'    border-radius: 13px;',
'',
'    font-size: 18px;',
'}',
'',
'.emad-guide-privacy h3 {',
'    margin:',
'        0 0 6px 0;',
'',
'    color:',
'        var(--emad-guide-text);',
'',
'    font-size: 1rem;',
'',
'    font-weight: 750;',
'}',
'',
'.emad-guide-privacy p {',
'    margin: 0;',
'',
'    color:',
'        var(--emad-guide-muted);',
'',
'    line-height: 1.55;',
'}',
'',
'.emad-guide-beta-text {',
'    margin-top: 8px !important;',
'',
'    font-size: 0.86rem;',
'}',
'',
'',
'/* ============================================================',
'   CTA',
'   ============================================================ */',
'',
'#emad-guide-cta {',
'    margin:',
'        42px 0 32px 0;',
'}',
'',
'.emad-guide-cta {',
'    padding:',
'        38px 30px;',
'',
'    text-align: center;',
'',
'    background:',
'        linear-gradient(',
'            135deg,',
'            #eef9f7 0%,',
'            #ffffff 100%',
'        );',
'',
'    border:',
'        1px solid #d8e9e6;',
'',
'    border-radius: 20px;',
'',
'    box-shadow:',
'        0 5px 18px',
'        rgba(0, 0, 0, 0.035);',
'}',
'',
'.emad-guide-cta h2 {',
'    margin:',
'        4px 0 9px 0;',
'}',
'',
'.emad-guide-cta p {',
'    max-width: 600px;',
'',
'    margin:',
'        0 auto;',
'',
'    color:',
'        var(--emad-guide-muted);',
'',
'    line-height: 1.6;',
'}',
'',
'.emad-guide-cta-action {',
'    display: flex;',
'',
'    justify-content: center;',
'    align-items: center;',
'',
'    margin-top: 22px;',
'}',
'',
'.emad-guide-start-button {',
'    display: inline-flex !important;',
'',
'    align-items: center;',
'    justify-content: center;',
'',
'    gap: 9px;',
'',
'    min-height: 48px;',
'',
'    padding:',
'        0 24px !important;',
'',
'    border-radius:',
'        11px !important;',
'',
'    font-size:',
'        0.95rem;',
'',
'    font-weight:',
'        700;',
'',
'    box-shadow:',
'        0 6px 16px',
'        rgba(17, 135, 127, 0.20);',
'',
'    transition:',
'        transform 0.15s ease,',
'        box-shadow 0.15s ease;',
'}',
'',
'.emad-guide-start-button:hover {',
'    transform:',
'        translateY(-2px);',
'',
'    box-shadow:',
'        0 9px 21px',
'        rgba(17, 135, 127, 0.27);',
'}',
'',
'.emad-guide-start-button:active {',
'    transform:',
'        translateY(0);',
'}',
'',
'',
'/* ============================================================',
'   TABLET',
'   ============================================================ */',
'',
'@media (max-width: 900px) {',
'',
'    #emad-guide-features .a-CardView-items {',
'        grid-template-columns:',
'            repeat(',
'                2,',
'                minmax(0, 1fr)',
'            ) !important;',
'    }',
'',
'    .emad-guide-dashboard-grid {',
'        grid-template-columns:',
'            repeat(',
'                2,',
'                minmax(0, 1fr)',
'            );',
'    }',
'',
'    .emad-guide-tip-list {',
'        grid-template-columns:',
'            minmax(0, 1fr);',
'    }',
'}',
'',
'',
'/* ============================================================',
'   MOBILE',
'   ============================================================ */',
'',
'@media (max-width: 640px) {',
'',
'    .t-Body-contentInner {',
'        padding-left: 12px;',
'        padding-right: 12px;',
'    }',
'',
'    #emad-guide-hero {',
'        margin-top: 12px;',
'        margin-bottom: 24px;',
'    }',
'',
'    .emad-guide-hero {',
'        padding:',
'            38px 18px 34px 18px;',
'',
'        border-radius: 18px;',
'    }',
'',
'    .emad-guide-hero-icon {',
'        width: 58px;',
'        height: 58px;',
'',
'        border-radius: 17px;',
'',
'        font-size: 24px;',
'    }',
'',
'    .emad-guide-hero-lead {',
'        font-size: 0.96rem;',
'    }',
'',
'    .emad-guide-hero-pills {',
'        gap: 7px;',
'    }',
'',
'    #emad-guide-features {',
'        margin-top: 22px;',
'        margin-bottom: 34px;',
'    }',
'',
'    #emad-guide-features .a-CardView-items {',
'        grid-template-columns:',
'            minmax(0, 1fr) !important;',
'    }',
'',
'    .emad-guide-section {',
'        margin:',
'            32px 0;',
'    }',
'',
'    .emad-guide-dashboard-grid {',
'        grid-template-columns:',
'            minmax(0, 1fr);',
'    }',
'',
'    .emad-guide-step {',
'        grid-template-columns:',
'            44px minmax(0, 1fr);',
'',
'        gap: 13px;',
'    }',
'',
'    .emad-guide-step-number {',
'        width: 44px;',
'        height: 44px;',
'',
'        border-radius: 13px;',
'    }',
'',
'    .emad-guide-step:not(:last-child)::before {',
'        left: 21px;',
'        top: 40px;',
'    }',
'',
'    .emad-guide-tips-section {',
'        padding: 18px;',
'    }',
'',
'    .emad-guide-privacy {',
'        flex-direction: column;',
'    }',
'',
'    .emad-guide-cta {',
'        padding:',
'            25px 18px;',
'    }',
'',
'    .emad-guide-start-button {',
'        width: 100%;',
'        max-width: 320px;',
'    }',
'}'))
,p_step_template=>4073832297226169690
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'23'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(99791647813556)
,p_plug_name=>'Breadcrumb'
,p_static_id=>'breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2532939663579242476
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_plug_item_display_point=>'ABOVE'
,p_menu_id=>wwv_flow_imp.id(25118539410634098746)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4073839682315169711
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(31193058799313)
,p_plug_name=>'Ready to Start'
,p_static_id=>'emad-guide-cta'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4502917002193490937
,p_plug_display_sequence=>70
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="emad-guide-cta">',
'',
'    <div>',
'        <span class="emad-guide-eyebrow">',
'            YOU''RE READY',
'        </span>',
'',
'        <h2>',
'            Start building your financial picture',
'        </h2>',
'',
'        <p>',
'            You can return to this guide anytime from the EmadFlow',
'            navigation menu.',
'        </p>',
'    </div>',
'',
'    <div class="emad-guide-cta-action">',
'',
'        <button',
'            type="button"',
'            class="t-Button t-Button--hot emad-guide-start-button"',
'            onclick="apex.submit(''COMPLETE_ONBOARDING'');">',
'',
'            <span>',
'                &P12_CTA_LABEL!HTML.',
'            </span>',
'',
'            <span',
'                class="fa fa-arrow-right"',
'                aria-hidden="true">',
'            </span>',
'',
'        </button>',
'',
'    </div>',
'',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(30898500799310)
,p_plug_name=>'Understanding Your Dashboard'
,p_static_id=>'emad-guide-dashboard'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4502917002193490937
,p_plug_display_sequence=>40
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<section class="emad-guide-section">',
'',
'    <div class="emad-guide-section-heading">',
'        <span class="emad-guide-eyebrow">YOUR DASHBOARD</span>',
'',
'        <h2>Understand what EmadFlow is telling you</h2>',
'',
'        <p>',
'            Home brings together several different views of your finances.',
'        </p>',
'    </div>',
'',
'    <div class="emad-guide-dashboard-grid">',
'',
'        <div class="emad-guide-info-card">',
'            <div class="emad-guide-info-icon">',
'                <span class="fa fa-money" aria-hidden="true"></span>',
'            </div>',
'',
'            <h3>Current Balance</h3>',
'',
'            <p>',
'                Your opening balance adjusted by the income and expenses',
'                recorded in EmadFlow.',
'            </p>',
'        </div>',
'',
'        <div class="emad-guide-info-card">',
'            <div class="emad-guide-info-icon">',
'                <span class="fa fa-calendar" aria-hidden="true"></span>',
'            </div>',
'',
'            <h3>Next 30 Days</h3>',
'',
'            <p>',
'                A forward-looking estimate based on your active recurring',
'                income and recurring expenses.',
'            </p>',
'        </div>',
'',
'        <div class="emad-guide-info-card">',
'            <div class="emad-guide-info-icon">',
'                <span class="fa fa-pie-chart" aria-hidden="true"></span>',
'            </div>',
'',
'            <h3>Spending</h3>',
'',
'            <p>',
'                Your recorded expenses grouped into categories so you can',
'                see where your money is going.',
'            </p>',
'        </div>',
'',
'        <div class="emad-guide-info-card">',
'            <div class="emad-guide-info-icon">',
'                <span class="fa fa-bullseye" aria-hidden="true"></span>',
'            </div>',
'',
'            <h3>Savings Progress</h3>',
'',
'            <p>',
'                Tracks how much you have saved against the targets you have',
'                created.',
'            </p>',
'        </div>',
'',
'        <div class="emad-guide-info-card">',
'            <div class="emad-guide-info-icon">',
'                <span class="fa fa-exchange" aria-hidden="true"></span>',
'            </div>',
'',
'            <h3>IOU Position</h3>',
'',
'            <p>',
'                Compares outstanding money owed to you with outstanding',
'                money you currently owe.',
'            </p>',
'        </div>',
'',
'        <div class="emad-guide-info-card">',
'            <div class="emad-guide-info-icon">',
'                <span class="fa fa-clock-o" aria-hidden="true"></span>',
'            </div>',
'',
'            <h3>Recent Activity</h3>',
'',
'            <p>',
'                A quick view of your latest recorded transactions without',
'                needing to open the full transaction report.',
'            </p>',
'        </div>',
'',
'    </div>',
'',
'</section>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(30612307799307)
,p_plug_name=>'What EmadFlow Can Do'
,p_static_id=>'emad-guide-features'
,p_region_template_options=>'#DEFAULT#:t-CardsRegion--hideHeader js-addHiddenHeadingRoleDesc'
,p_plug_template=>2074200852440250129
,p_plug_display_sequence=>20
,p_plug_grid_column_span=>12
,p_plug_item_display_point=>'ABOVE'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select',
'    1 as sort_order,',
'    ''Transactions'' as card_title,',
'    ''Income & Expenses'' as card_subtitle,',
'    ''Record everyday income and expenses so your dashboard reflects your actual financial activity.'' as card_body,',
'    ''Daily Money'' as card_badge,',
'    ''fa fa-exchange'' as card_icon',
'from dual',
'',
'union all',
'',
'select',
'    2,',
'    ''Recurring Money'',',
'    ''Plan Ahead'',',
'    ''Add salary, rent, subscriptions, bills and other recurring items to understand what is coming next.'',',
'    ''Cash Flow'',',
'    ''fa fa-repeat''',
'from dual',
'',
'union all',
'',
'select',
'    3,',
'    ''Savings Goals'',',
'    ''Build Towards Something'',',
'    ''Create financial targets, record your saved amount and watch your progress grow over time.'',',
'    ''Goals'',',
'    ''fa fa-bullseye''',
'from dual',
'',
'union all',
'',
'select',
'    4,',
'    ''IOUs'',',
'    ''Lent & Borrowed'',',
'    ''Keep track of money you have lent, money you owe and repayments without relying on memory.'',',
'    ''Money Between People'',',
'    ''fa fa-users''',
'from dual',
'',
'order by 1'))
,p_lazy_loading=>false
,p_plug_source_type=>'NATIVE_CARDS'
,p_plug_query_num_rows_type=>'SCROLL'
,p_show_total_row_count=>false
);
wwv_flow_imp_page.create_card(
 p_id=>wwv_flow_imp.id(30664325799308)
,p_region_id=>wwv_flow_imp.id(30612307799307)
,p_layout_type=>'GRID'
,p_title_adv_formatting=>false
,p_title_column_name=>'CARD_TITLE'
,p_sub_title_adv_formatting=>false
,p_sub_title_column_name=>'CARD_SUBTITLE'
,p_body_adv_formatting=>false
,p_body_column_name=>'CARD_BODY'
,p_second_body_adv_formatting=>false
,p_icon_source_type=>'DYNAMIC_CLASS'
,p_icon_class_column_name=>'CARD_ICON'
,p_icon_position=>'START'
,p_badge_column_name=>'CARD_BADGE'
,p_media_adv_formatting=>false
,p_pk1_column_name=>'SORT_ORDER'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(30504232799306)
,p_plug_name=>'Welcome Hero'
,p_static_id=>'emad-guide-hero'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4502917002193490937
,p_plug_display_sequence=>10
,p_plug_grid_column_span=>12
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="emad-guide-hero">',
'    <div class="emad-guide-hero-icon">',
'        <span class="fa fa-badge-dollar" aria-hidden="true"></span>',
'    </div>',
'',
'    <div class="emad-guide-beta-badge">',
'        PRIVATE BETA',
'    </div>',
'',
'    <h1>',
'        Welcome to EmadFlow',
'    </h1>',
'',
'    <p class="emad-guide-welcome-name">',
'        Hello, &G_USER_DISPLAY_NAME!HTML.',
'    </p>',
'',
'    <p class="emad-guide-hero-lead">',
'        A simple personal finance workspace for understanding your money,',
'        planning upcoming cash flow, building savings goals and keeping track',
'        of money you lend or borrow.',
'    </p>',
'',
'    <div class="emad-guide-hero-pills">',
'        <span>',
'            <span class="fa fa-lock" aria-hidden="true"></span>',
'            Your account',
'        </span>',
'',
'        <span>',
'            <span class="fa fa-line-chart" aria-hidden="true"></span>',
'            Financial overview',
'        </span>',
'',
'        <span>',
'            <span class="fa fa-mobile" aria-hidden="true"></span>',
'            Mobile friendly',
'        </span>',
'    </div>',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(31097271799312)
,p_plug_name=>'Privacy and Beta'
,p_static_id=>'emad-guide-privacy'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4502917002193490937
,p_plug_display_sequence=>60
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="emad-guide-privacy">',
'',
'    <div class="emad-guide-privacy-icon">',
'        <span class="fa fa-lock" aria-hidden="true"></span>',
'    </div>',
'',
'    <div>',
'        <h3>Your EmadFlow account is separate from other users</h3>',
'',
'        <p>',
'            Your financial records are associated with your authenticated',
'            EmadFlow account. Other signed-in users have their own profile,',
'            transactions, recurring items, savings goals and IOUs.',
'        </p>',
'',
'        <p class="emad-guide-beta-text">',
'            EmadFlow is currently a private beta. Please avoid treating it',
'            as a replacement for official bank statements, accounting',
'            records or professional financial advice.',
'        </p>',
'    </div>',
'',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(30749881799309)
,p_plug_name=>'Get Started'
,p_static_id=>'emad-guide-steps'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4502917002193490937
,p_plug_display_sequence=>30
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<section class="emad-guide-section">',
'',
'    <div class="emad-guide-section-heading">',
'        <span class="emad-guide-eyebrow">GETTING STARTED</span>',
'',
'        <h2>Start using EmadFlow in five simple steps</h2>',
'',
'        <p>',
'            You do not need to configure everything at once.',
'            Build your financial picture gradually.',
'        </p>',
'    </div>',
'',
'    <div class="emad-guide-steps">',
'',
'        <div class="emad-guide-step">',
'            <div class="emad-guide-step-number">1</div>',
'',
'            <div class="emad-guide-step-content">',
'                <h3>Set your starting position</h3>',
'',
'                <p>',
'                    Open <strong>My Profile</strong> and enter your opening',
'                    balance. This gives EmadFlow a starting point for your',
'                    current balance calculation.',
'                </p>',
'            </div>',
'        </div>',
'',
'        <div class="emad-guide-step">',
'            <div class="emad-guide-step-number">2</div>',
'',
'            <div class="emad-guide-step-content">',
'                <h3>Add recurring income and expenses</h3>',
'',
'                <p>',
'                    Add salary, rent, insurance, subscriptions and other',
'                    repeating payments. EmadFlow uses these to build your',
'                    upcoming cash-flow forecast.',
'                </p>',
'            </div>',
'        </div>',
'',
'        <div class="emad-guide-step">',
'            <div class="emad-guide-step-number">3</div>',
'',
'            <div class="emad-guide-step-content">',
'                <h3>Record everyday transactions</h3>',
'',
'                <p>',
'                    Add income and expenses as they occur. Your financial',
'                    summary, charts and recent activity will update from',
'                    these records.',
'                </p>',
'            </div>',
'        </div>',
'',
'        <div class="emad-guide-step">',
'            <div class="emad-guide-step-number">4</div>',
'',
'            <div class="emad-guide-step-content">',
'                <h3>Create goals and track IOUs</h3>',
'',
'                <p>',
'                    Use Savings Goals for targets you are working towards,',
'                    and IOUs for money you have lent or borrowed.',
'                </p>',
'            </div>',
'        </div>',
'',
'        <div class="emad-guide-step">',
'            <div class="emad-guide-step-number">5</div>',
'',
'            <div class="emad-guide-step-content">',
'                <h3>Use Home as your financial dashboard</h3>',
'',
'                <p>',
'                    Return to Home to review your balance, upcoming cash',
'                    flow, spending categories, savings progress and recent',
'                    activity in one place.',
'                </p>',
'            </div>',
'        </div>',
'',
'    </div>',
'',
'</section>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(30920420799311)
,p_plug_name=>'Tips for Using EmadFlow'
,p_static_id=>'emad-guide-tips'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4502917002193490937
,p_plug_display_sequence=>50
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<section class="emad-guide-section emad-guide-tips-section">',
'',
'    <div class="emad-guide-section-heading">',
'        <span class="emad-guide-eyebrow">GOOD TO KNOW</span>',
'',
'        <h2>A few tips for getting useful results</h2>',
'    </div>',
'',
'    <div class="emad-guide-tip-list">',
'',
'        <div class="emad-guide-tip">',
'            <span class="fa fa-check-circle" aria-hidden="true"></span>',
'',
'            <div>',
'                <strong>Keep transactions current.</strong>',
'                <p>',
'                    The dashboard becomes more useful when your recorded',
'                    income and expenses reflect what has actually happened.',
'                </p>',
'            </div>',
'        </div>',
'',
'        <div class="emad-guide-tip">',
'            <span class="fa fa-check-circle" aria-hidden="true"></span>',
'',
'            <div>',
'                <strong>Use recurring items for future planning.</strong>',
'                <p>',
'                    A recurring item is a forecast. A transaction records',
'                    money that has actually occurred.',
'                </p>',
'            </div>',
'        </div>',
'',
'        <div class="emad-guide-tip">',
'            <span class="fa fa-check-circle" aria-hidden="true"></span>',
'',
'            <div>',
'                <strong>Review your savings amounts.</strong>',
'                <p>',
'                    Savings progress only changes when you update the amount',
'                    saved against a goal.',
'                </p>',
'            </div>',
'        </div>',
'',
'        <div class="emad-guide-tip">',
'            <span class="fa fa-check-circle" aria-hidden="true"></span>',
'',
'            <div>',
'                <strong>Record IOU repayments.</strong>',
'                <p>',
'                    Recording repayments keeps outstanding balances and your',
'                    Net IOU Position accurate.',
'                </p>',
'            </div>',
'        </div>',
'',
'    </div>',
'',
'</section>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(31237707799314)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(31193058799313)
,p_button_name=>'COMPLETE_ONBOARDING'
,p_static_id=>'complete-onboarding'
,p_show_as_disabled=>false
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#:t-Button--iconLeft'
,p_button_template_id=>2084305881903810008
,p_button_is_hot=>'Y'
,p_button_image_alt=>'EmadFlow'
,p_button_condition_type=>'NEVER'
,p_icon_css_classes=>'fa-arrow-right'
,p_grid_new_row=>'Y'
);
wwv_flow_imp_page.create_page_branch(
 p_id=>wwv_flow_imp.id(31499684799316)
,p_branch_name=>'Go to Home After Onboarding'
,p_branch_action=>'f?p=&APP_ID.:1:&SESSION.::&DEBUG.:1::&success_msg=#SUCCESS_MSG#'
,p_branch_point=>'AFTER_PROCESSING'
,p_branch_type=>'REDIRECT_URL'
,p_branch_sequence=>10
,p_branch_condition_type=>'REQUEST_EQUALS_CONDITION'
,p_branch_condition=>'COMPLETE_ONBOARDING'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(31562542799317)
,p_name=>'P12_CTA_LABEL'
,p_item_sequence=>80
,p_source_type=>'ALWAYS_NULL'
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'Y')).to_clob
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(31357956799315)
,p_process_sequence=>10
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'Complete Onboarding'
,p_static_id=>'complete-onboarding'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_onboarding_completed_yn',
'        bf_user_profile.onboarding_completed_yn%type;',
'begin',
'',
'    begin',
'        select onboarding_completed_yn',
'        into l_onboarding_completed_yn',
'        from bf_user_profile',
'        where app_user = v(''APP_USER'');',
'',
'    exception',
'        when no_data_found then',
'            raise_application_error(',
'                -20120,',
'                ''Unable to locate your EmadFlow profile.''',
'            );',
'    end;',
'',
'',
'    if l_onboarding_completed_yn = ''N'' then',
'',
'        update bf_user_profile',
'        set',
'            onboarding_completed_yn = ''Y'',',
'            onboarding_completed_at = systimestamp,',
'            updated_at = systimestamp',
'        where app_user = v(''APP_USER'');',
'',
'    end if;',
'',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'COMPLETE_ONBOARDING'
,p_process_when_type=>'REQUEST_EQUALS_CONDITION'
,p_internal_uid=>9014141494406344
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(31701515799318)
,p_process_sequence=>10
,p_process_point=>'BEFORE_HEADER'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'Load Guide CTA Label'
,p_static_id=>'load-guide-cta-label'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    l_onboarding_completed_yn',
'        bf_user_profile.onboarding_completed_yn%type;',
'begin',
'',
'    begin',
'        select onboarding_completed_yn',
'        into l_onboarding_completed_yn',
'        from bf_user_profile',
'        where app_user = v(''APP_USER'');',
'',
'    exception',
'        when no_data_found then',
'            l_onboarding_completed_yn := ''N'';',
'    end;',
'',
'    if l_onboarding_completed_yn = ''Y'' then',
'        :P12_CTA_LABEL := ''Back to Dashboard'';',
'    else',
'        :P12_CTA_LABEL := ''Start Using EmadFlow'';',
'    end if;',
'',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>9014485053406347
);
wwv_flow_imp.component_end;
end;
/
